
--Tạo database.
CREATE DATABASE QLTuyenDung
go

--Sử dụng database vừa tạo.
USE QLTuyenDung
go

--Tạo bảng.
--Nhân viên.
CREATE TABLE NHANVIEN (
	MaNV INT IDENTITY(1, 1),
	TenNV NVARCHAR(100) NOT NULL,
	NgayGiaNhap DATE NOT NULL,
	--Thông tin cá nhân.
	CCCD CHAR(12) NOT NULL,
	GioiTinh NVARCHAR(3) CHECK (GioiTinh IN ('Nam', N'Nữ')),
	NgaySinh DATE NOT NULL,
	SDT VARCHAR(11) CHECK (SDT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' OR SDT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),

    CONSTRAINT CK_CCCD CHECK (CCCD LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MaNV)
)
go
--Doanh nghiệp.
CREATE TABLE DOANHNGHIEP (
	MaThue CHAR(10) NOT NULL,
	--Thông tin doanh nghiệp.
	NgayDangKy DATE NOT NULL,
	LogoPath NVARCHAR(130),

	CONSTRAINT CK_MaThue CHECK (MaThue LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	CONSTRAINT PK_DOANHNGHIEP PRIMARY KEY (MaThue)
)
go
--Phiếu đăng ký thông tin.
CREATE TABLE PDK_THONGTIN (
	TenCTy NVARCHAR(255) NOT NULL,
    MaThue CHAR(10) NOT NULL,
	MaNV INT NOT NULL,
    NguoiDaiDien NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(255) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
	TinhHopLe NVARCHAR(10) NOT NULL CHECK (TinhHopLe IN ('OK', 'NOT OK', 'REJECT')),

    CONSTRAINT FK_PDKTT_DOANHNGHIEP FOREIGN KEY (MaThue) REFERENCES DOANHNGHIEP (MaThue),
	CONSTRAINT FK_PDKTT_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN (MaNV),
    CONSTRAINT PK_PDK_THONGTIN PRIMARY KEY (TenCTy, MaThue)
);
go
--Phiếu cung cấp thông tin đăng tuyển.
CREATE TABLE PCC_TT_DANGTUYEN (
	MaPhieu INT IDENTITY(1, 1),
	ViTriTuyenDung NVARCHAR(100) NOT NULL,
	SLTuyenDung INT NOT NULL,
	KTGDangTuyen INT NOT NULL,
	ThongTinYeuCau NVARCHAR(255) NOT NULL,

	CONSTRAINT PK_PCC_TT_DANGTUYEN PRIMARY KEY (MaPhieu)
)
go
--Bảng lưu Doanh nghiệp và Thông tin đăng tuyển.
CREATE TABLE DOANHNGHIEP_DANGTUYEN (
	MaThue CHAR(10) NOT NULL,
	MaPhieu INT NOT NULL,
	MaNV INT NOT NULL,
	TGDangTuyen DATE NOT NULL,
	HinhThuc NVARCHAR(20) NOT NULL CHECK (HinhThuc IN ('BAOGIAY', 'BANNER', 'MEDIA')),
	TinhHopLe NVARCHAR(10) NOT NULL CHECK (TinhHopLe IN ('OK', 'NOT OK', 'REJECT')),

	CONSTRAINT FK_DNDT_DOANHNGHIEP FOREIGN KEY (MaThue) REFERENCES DOANHNGHIEP (MaThue),
	CONSTRAINT FK_DNDT_TTDANGTUYEN FOREIGN KEY (MaPhieu) REFERENCES PCC_TT_DANGTUYEN (MaPhieu),
	CONSTRAINT FK_DNDT_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN (MaNV),
	CONSTRAINT PK_DOANHNGHIEP_DANGTUYEN PRIMARY KEY (MaThue, MaPhieu)
)
go
--Phiếu đăng ký quảng cáo.
CREATE TABLE PDK_QUANGCAO (
	MaPhieu INT IDENTITY(1, 1),
	MaThue CHAR(10) NOT NULL,
	MaPhieuDT INT NOT NULL,
	MaNV INT NOT NULL,

	CONSTRAINT FK_PDKQC_DNDT FOREIGN KEY (MaThue, MaPhieuDT) REFERENCES DOANHNGHIEP_DANGTUYEN (MaThue, MaPhieu),
	CONSTRAINT FK_PDKQC_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN (MaNV),
	CONSTRAINT PK_PDK_QUANGCAO PRIMARY KEY (MaPhieu)
)
go
--Hóa đơn.
CREATE TABLE HOADON (
	MaHoaDon INT IDENTITY(1, 1),
	MaThue CHAR(10) NOT NULL,
	MaPhieu INT NOT NULL,
	SoTien INT NOT NULL,
	DaNhan INT NOT NULL,
	BillPath NVARCHAR (130),

	CONSTRAINT FK_HOADON_DNDT FOREIGN KEY (MaThue, MaPhieu) REFERENCES DOANHNGHIEP_DANGTUYEN (MaThue, MaPhieu),
	CONSTRAINT CK_DaNhan CHECK (DaNhan <= SoTien),
	CONSTRAINT PK_HOADON PRIMARY KEY (MaHoaDon)
)
go
--Hồ sơ ứng viên.
CREATE TABLE HSUV (
	CCCD CHAR(12) NOT NULL,
	Ten NVARCHAR(100) NOT NULL,
	--Thông tin cá nhân.
	GioiTinh NVARCHAR(3) CHECK (GioiTinh IN ('Nam', N'Nữ')),
	NgaySinh DATE NOT NULL,
	SDT VARCHAR(11) CHECK (SDT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' OR SDT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),

	CONSTRAINT CK_CCCD_HSUV CHECK (CCCD LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	CONSTRAINT PK_HSUV PRIMARY KEY (CCCD)
)
go
--Phiếu đăng ký ứng tuyển.
CREATE TABLE PDK_UNGTUYEN (
	MaPhieu INT IDENTITY(1, 1),
	MaNV INT NOT NULL,
	CCCD CHAR(12) NOT NULL,
	ViTri NVARCHAR(255) NOT NULL,
	TinhHopLe NVARCHAR(10) NOT NULL CHECK (TinhHopLe IN ('OK', 'NOT OK', 'REJECT')), 
	GhiChu NVARCHAR(255),
	CVPath NVARCHAR(130),

	CONSTRAINT FK_PDKUT_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN (MaNV),
	CONSTRAINT FK_PDKUT_HSUV FOREIGN KEY (CCCD) REFERENCES HSUV (CCCD),
	CONSTRAINT PK_PDK_UNGTUYEN PRIMARY KEY (MaPhieu)
)
go
--Bảng lưu thông tin duyệt hồ sơ.
CREATE TABLE DUYETHOSO (
	MaPhieuQC INT NOT NULL,
	MaPhieuUT INT NOT NULL,
	ThoiGian DATE NOT NULL,

	CONSTRAINT FK_DUYETHS_PDKQC FOREIGN KEY (MaPhieuQC) REFERENCES PDK_QUANGCAO (MaPhieu),
	CONSTRAINT FK_DUYETHS_PDKUT FOREIGN KEY (MaPhieuUT) REFERENCES PDK_UNGTUYEN (MaPhieu),
	CONSTRAINT PK_DUYETHOSO PRIMARY KEY (MaPhieuQC, MaPhieuUT)
)
go
--Chiến lược ưu đãi.
CREATE TABLE UUDAI (
	MaUD INT IDENTITY(1, 1),
	TenChienLuoc NVARCHAR(255) NOT NULL,
	ChiTiet NVARCHAR(255) NOT NULL,

	CONSTRAINT PK_UUDAI PRIMARY KEY (MaUD)
)
go
--Danh sách doanh nghiệp tiềm năng.
CREATE TABLE DN_TIEMNANG (
	MaThue CHAR(10) NOT NULL,
	SLUngTuyen INT NOT NULL,
	MaNV INT NOT NULL,
	MaUD INT,

	CONSTRAINT FK_DNTN_DOANHNGHIEP FOREIGN KEY (MaThue) REFERENCES DOANHNGHIEP (MaThue),
	CONSTRAINT FK_DNTN_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN (MaNV),
	CONSTRAINT FK_DNTN_UUDAI FOREIGN KEY (MaUD) REFERENCES UUDAI (MaUD),
	CONSTRAINT PK_DN_TIEMNANG PRIMARY KEY (MaThue)
)
go


-- Tạo các bảng lưu trữ tài khoản
CREATE TABLE QUYEN (
	MaQuyen int NOT NULL,
	TenQuyen nvarchar(50)

	CONSTRAINT PK_QUYEN PRIMARY KEY (MaQuyen)
)
GO

CREATE TABLE TAIKHOAN (
	MaTK NVARCHAR(50) NOT NULL,
	TenTaiKhoan NVARCHAR(50) NOT NULL,
	MatKhau NVARCHAR(100),
	MaQuyen INT,
	
	CONSTRAINT FK_TAIKHOAN_QUYEN FOREIGN KEY (MaQuyen) REFERENCES QUYEN(MaQuyen),
	CONSTRAINT PK_TAIKHOAN PRIMARY KEY (MaTK)
)
GO

CREATE TABLE PHEDUYET (
	MaPD INT IDENTITY(1, 1),
	MaPhieuUT INT NOT NULL,
	MaThue CHAR(10) NOT NULL,
	TrangThai INT
)